src/main/java/org/archivemanager/model/Collection.java
package org.archivemanager.model;
import java.util.ArrayList;
import java.util.List;

import org.heed.openapps.Permission;


public class Collection extends Result {
	private String url;	
	private String bioNote;
	private String scopeNote;
	private String abstractNote;
	private String container;
	private String dateExpression;	
	private String comment = "";
	private String code;
	private String identifier;
	private String accessionDate;
	private String begin;
	private String end;
	private String bulkBegin;
	private String bulkEnd;
	private String language;
	private String extentUnits;
	private String extentNumber;
	private boolean restrictions;
	private boolean internal;
	private boolean isPublic;
	
	private List<Category> categories = new ArrayList<Category>();
	private List<Note> notes = new ArrayList<Note>();
	private List<NamedEntity> people = new ArrayList<NamedEntity>();
	private List<NamedEntity> corporations = new ArrayList<NamedEntity>();
	private List<Subject> subjects = new ArrayList<Subject>();
	private List<DigitalObject> digitalObjects = new ArrayList<DigitalObject>();
	private List<WebLink> weblinks = new ArrayList<WebLink>();
	private List<Permission> permissions = new ArrayList<Permission>();
	
	public Collection() {}
	public Collection(long id, String title, String description, String contentType) {
		super(id, title, description, contentType);
	}
		
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getBegin() {
		return begin;
	}
	public void setBegin(String begin) {
		this.begin = begin;
	}
	public String getEnd() {
		return end;
	}
	public void setEnd(String end) {
		this.end = end;
	}
	public List<Category> getCategories() {
		return categories;
	}
	public void setCategories(List<Category> categories) {
		this.categories = categories;
	}
	public String getContainer() {
		return container;
	}
	public void setContainer(String container) {
		this.container = container;
	}
	public String getDateExpression() {
		return dateExpression;
	}
	public void setDateExpression(String dateExpression) {
		this.dateExpression = dateExpression;
	}
	public String getBioNote() {
		return bioNote;
	}
	public void setBioNote(String bioNote) {
		this.bioNote = bioNote;
	}
	public String getScopeNote() {
		return scopeNote;
	}
	public void setScopeNote(String scopeNote) {
		this.scopeNote = scopeNote;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getIdentifier() {
		return identifier;
	}
	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}
	public String getAccessionDate() {
		return accessionDate;
	}
	public void setAccessionDate(String accessionDate) {
		this.accessionDate = accessionDate;
	}
	public String getBulkBegin() {
		return bulkBegin;
	}
	public void setBulkBegin(String bulkBegin) {
		this.bulkBegin = bulkBegin;
	}
	public String getBulkEnd() {
		return bulkEnd;
	}
	public void setBulkEnd(String bulkEnd) {
		this.bulkEnd = bulkEnd;
	}
	public String getLanguage() {
		return language;
	}
	public void setLanguage(String language) {
		this.language = language;
	}
	public String getExtentUnits() {
		return extentUnits;
	}
	public void setExtentUnits(String extentUnits) {
		this.extentUnits = extentUnits;
	}
	public String getExtentNumber() {
		return extentNumber;
	}
	public void setExtentNumber(String extentNumber) {
		this.extentNumber = extentNumber;
	}
	public boolean isRestrictions() {
		return restrictions;
	}
	public void setRestrictions(boolean restrictions) {
		this.restrictions = restrictions;
	}
	public boolean isInternal() {
		return internal;
	}
	public void setInternal(boolean internal) {
		this.internal = internal;
	}
	public boolean isPublic() {
		return isPublic;
	}
	public void setPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}
	public String getAbstractNote() {
		return abstractNote;
	}
	public void setAbstractNote(String abstractNote) {
		this.abstractNote = abstractNote;
	}
	public List<Note> getNotes() {
		return notes;
	}	
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public void setNotes(List<Note> notes) {
		this.notes = notes;
	}

	public List<NamedEntity> getPeople() {
		return people;
	}

	public void setPeople(List<NamedEntity> people) {
		this.people = people;
	}

	public List<NamedEntity> getCorporations() {
		return corporations;
	}

	public void setCorporations(List<NamedEntity> corporations) {
		this.corporations = corporations;
	}

	public List<Subject> getSubjects() {
		return subjects;
	}

	public void setSubjects(List<Subject> subjects) {
		this.subjects = subjects;
	}

	public List<DigitalObject> getDigitalObjects() {
		return digitalObjects;
	}

	public void setDigitalObjects(List<DigitalObject> digitalObjects) {
		this.digitalObjects = digitalObjects;
	}

	public List<WebLink> getWeblinks() {
		return weblinks;
	}
	public void setWeblinks(List<WebLink> weblinks) {
		this.weblinks = weblinks;
	}
	public List<Permission> getPermissions() {
		return permissions;
	}
	public void setPermissions(List<Permission> permissions) {
		this.permissions = permissions;
	}
	
}

src/main/java/org/archivemanager/model/Result.java
package org.archivemanager.model;


public class Result {
	private long id;
	private long user;
	private String username;
	private String name = "";
	private String description = "";
	private String contentType = "";
		
	
	public Result() {}
	public Result(long id, String name) {
		this.id = id;
		this.name = name;
	}
	public Result(long id, String name, String description, String contentType) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.contentType = contentType;
	}
			
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getContentType() {
		return contentType;
	}
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}	
	public long getUser() {
		return user;
	}
	public void setUser(long user) {
		this.user = user;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
		
}

src/main/java/org/archivemanager/model/ResultSet.java
package org.archivemanager.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ResultSet implements Serializable {
	private static final long serialVersionUID = 7475159832192849105L;
	private String baseUrl;
	private String query;
	private String label;
	private String sort;
	private int page;
	private int pageSize = 10;
	private int pageCount;
	private int start;
	private int end;
	private int resultCount;
	private long time;
	private List<Breadcrumb> breadcrumbs = new ArrayList<Breadcrumb>();
	private List<Result> results = new ArrayList<Result>();
	private List<Attribute> attributes = new ArrayList<Attribute>();
	private List<Paging> paging = new ArrayList<Paging>();
	
	public ResultSet() {}
	
	
	public String getBaseUrl() {
		return baseUrl;
	}
	public void setBaseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
	}
	public String getQuery() {
		return query;
	}
	public void setQuery(String query) {
		this.query = query;
	}
	public String getLabel() {
		return label;
	}
	public void setLabel(String label) {
		this.label = label;
	}
	public String getSort() {
		return sort;
	}
	public void setSort(String sort) {
		this.sort = sort;
	}
	public int getPage() {
		return page;
	}
	public void setPage(int page) {
		this.page = page;
	}
	public int getPageSize() {
		return pageSize;
	}
	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}
	public int getPageCount() {
		return pageCount;
	}
	public void setPageCount(int pageCount) {
		this.pageCount = pageCount;
	}
	public int getStart() {
		return start;
	}
	public void setStart(int start) {
		this.start = start;
	}
	public int getEnd() {
		return end;
	}
	public void setEnd(int end) {
		this.end = end;
	}
	public int getResultCount() {
		return resultCount;
	}
	public long getTime() {
		return time;
	}
	public void setTime(long time) {
		this.time = time;
	}
	public void setResultCount(int resultCount) {
		this.resultCount = resultCount;
	}
	public Breadcrumb getLastBreadcrumb() {
		if(breadcrumbs != null && breadcrumbs.size() > 0) {
			return breadcrumbs.get(breadcrumbs.size() - 1);
		}
		return null;
	}
	public List<Breadcrumb> getBreadcrumbs() {
		return breadcrumbs;
	}
	public void setBreadcrumbs(List<Breadcrumb> breadcrumbs) {
		this.breadcrumbs = breadcrumbs;
	}
	public List<Result> getResults() {
		return results;
	}
	public void setResults(List<Result> results) {
		this.results = results;
	}
	public List<Attribute> getAttributes() {
		return attributes;
	}
	public void setAttributes(List<Attribute> attributes) {
		this.attributes = attributes;
	}
	public List<Paging> getPaging() {
		return paging;
	}
	public void setPaging(List<Paging> paging) {
		this.paging = paging;
	}
	
}

src/main/java/org/archivemanager/model/Video.java
package org.archivemanager.model;


public class Video extends Item {
	private String rendition;
	private String avatar;
	
	
	public Video(long id, String title, String description, String contentType) {
		super(id, title, description, contentType);
	}
	
	public String getRendition() {
		return rendition;
	}
	public void setRendition(String rendition) {
		this.rendition = rendition;
	}
	public String getAvatar() {
		return avatar;
	}
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}
		
}

src/main/java/org/archivemanager/server/web/SearchController.java
package org.archivemanager.server.web;
import java.util.Map;
import java.util.logging.Logger;

import org.heed.openapps.QName;
import org.heed.openapps.data.Sort;
import org.archivemanager.RepositoryModel;
import org.heed.openapps.search.EntityQuery;
import org.heed.openapps.search.EntityResultSet;
import org.heed.openapps.search.SearchService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;


@Controller
@RequestMapping("/service/search")
public class SearchController {
	private final static Logger log = Logger.getLogger(SearchController.class.getName());
	@Autowired private SearchService searchService;
	
	@GetMapping("/default")
	public String getDefault(Map<String, Object> model) {
		
		return "search/default";
	}
	@GetMapping("/collections")
	public String getCollections(@RequestParam(defaultValue="",required=false) String query, 
			@RequestParam(required=false) String code, 
			@RequestParam(defaultValue="0",required=false) int start, 
			@RequestParam(defaultValue="10",required=false) int end, 
			@RequestParam(required=false) String sort, 
			Map<String, Object> model) {
		if(query == null || query.length() == 0) query = "all results";
		String[] sorts = (sort != null) ? sort.split(",") : new String[0];
		
		EntityQuery searchRequest = getSearchRequest(RepositoryModel.COLLECTION, query, start, end, sorts, false);
		searchRequest.setType(EntityQuery.TYPE_SEARCH);
		searchRequest.addParameter(RepositoryModel.CODE.getLocalName(), code);
		
		EntityResultSet results = searchService.search(searchRequest);
		model.put("results", results);
		
		return "/search/collections";
	}
	
	protected EntityQuery getSearchRequest(QName qname, String query, int startRow, int endRow, String[] sorts, boolean attributes) {
		EntityQuery sQuery = new EntityQuery(qname, query);
		sQuery.setFetchAttributes(attributes);
		sQuery.setStartRow(startRow);
		sQuery.setEndRow(endRow);
		if(sorts != null) {
			for(String sort : sorts) {
				Sort lSort = null;
				String[] sortStrings = sort.split(",");
				for(String sortStr : sortStrings) {
					String[] s = sortStr.split(" ");
					if(s.length == 2) {
						boolean reverse = s[1].equals("asc") ? true : false;
						if(s[0].endsWith("_")) lSort = new Sort(Sort.LONG, s[0], reverse);
						else lSort = new Sort(Sort.STRING, s[0], reverse);						
					} else if(s.length == 1) {
						if(s[0].endsWith("_")) lSort = new Sort(Sort.LONG, s[0], true);
						else lSort = new Sort(Sort.STRING, s[0], false);
					}
					sQuery.addSort(lSort);
				}
			}
		}				
		return sQuery;
	}
}

src/main/webapp/WEB-INF/jsp/search/archive_results.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/portlet_2_0" prefix="portlet" %>
<%@ taglib uri="http://liferay.com/tld/theme" prefix="liferay-theme" %>

<portlet:defineObjects />
<liferay-theme:defineObjects />

<div id="archive-search-results">
	<table style="width:100%;">
		<tr>
			<td>
				<table class="archive-search-tools">
					<tbody>					
						<tr>
							<td class="archive-results-summary">
								<%@ include file="include/results_header.jsp" %>
							</td>					
						</tr>					
					</tbody>
				</table>
	
				<table class="archive-results-table">
					<tbody>
						<c:forEach items="${resultset.results}" var="result" varStatus="rstatus">
							<tr>						
								<td class="archive-results-result">
									<table style="width:100%;">
										<tr>
											<td style="width:50px;">
												<div class="archive-results-contentType">
													<c:out value="${result.contentType}" escapeXml="false" />
												</div>
											</td>
											<td style="vertical-align:top;">
												<div class="archive-results-title">
													<c:if test="${result.contentType == 'collection'}">
														<c:choose>
															<c:when test="${result.url != null}">
																<a href="${result.url}">
															</c:when>
															<c:otherwise>
																<a href="/collections/collection?id=<c:out value="${result.id}" />">
															</c:otherwise>
														</c:choose>
													</c:if>	
													<c:if test="${result.contentType == 'person' || result.contentType == 'corporation'}">
														<a href="/collections/notable-figure?id=<c:out value="${result.id}" />">
													</c:if>
													<c:if test="${result.contentType == 'subject'}">
														<a href="/collections/subject?id=<c:out value="${result.id}" />">
													</c:if>
													<c:if test="${result.contentType != 'subject' && result.contentType != 'person' && result.contentType != 'corporation' && result.contentType != 'collection'}">
														<a href="/collections/item?id=<c:out value="${result.id}" />">
													</c:if>
														
													<c:choose>	
														<c:when test="${result.title != null}">
															<c:out value="${result.title}" escapeXml="false" />
														</c:when>
														<c:otherwise>
															no title
														</c:otherwise>
													</c:choose>
													</a>									
												</div>
											</td>
										</tr>
										<c:if test="${description == 'true'}">
										<tr>
											<td style="width:50px;"></td>
											<td style="vertical-align:top;">
												<div class="archive-results-description">
													<c:out value="${result.description}" />
												</div>
											</td>
										</tr>
										</c:if>
									</table>									
								</td>
							</tr>
						</c:forEach>
					</tbody>
				</table>
	
				<table class="archive-results-paging">
					<tbody><tr>
						<td></td>
						<td class="tools_right">
							<c:forEach items="${resultset.paging}" var="page" varStatus="pstatus">
								<c:choose>
									<c:when test="${page.name == currentPage}">
										<b><c:out value="${page.name}" /></b>
									</c:when>
									<c:otherwise>
										<a href="<c:out value="${baseUrl}" />?<c:out value="${page.query}" />"><c:out value="${page.name}" /></a>
									</c:otherwise>
								</c:choose>
							</c:forEach>	
						</td>
					</tr></tbody>
				</table>
			</td>		
		</tr>
	</table>
</div>

src/main/webapp/WEB-INF/jsp/search/collections.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<div id="archive-search-results">
	<table style="width:100%;">
		<tr>
			<td>
				<table class="archive-search-tools">
					<tbody>					
						<tr>
							<td class="archive-results-summary">
								<c:if test="${not empty resultset.results}">
									<c:if test="${resultset.start != 0}">
										Results <b><c:out value="${resultset.start}" /> - <c:out value="${resultset.end}" /></b> of <b><c:out value="${resultset.resultCount}" /></b> for <b><c:out value="${resultset.lastBreadcrumb.name}" /></b>
									</c:if>
									<c:if test="${resultset.start == 0}">
										Results <b>1 - <c:out value="${resultset.end}" /></b> of <b><c:out value="${resultset.resultCount}" /></b> for <b><c:out value="${resultset.lastBreadcrumb.name}" /></b>
									</c:if>
								</c:if>
								<c:if test="${empty resultset.results}">
									No Results for <b><c:out value="${resultset.lastBreadcrumb.name}" /></b>
								</c:if>
							</td>					
						</tr>					
					</tbody>
				</table>
	
				<table class="archive-results-table">
					<tbody>
						<c:forEach items="${resultset.results}" var="result" varStatus="rstatus">
							<tr>						
								<td class="archive-results-result">
									<div class="archive-results-title">
										<c:choose>
											<c:when test="${result.url != null}">
												<a href="${result.url}">
											</c:when>
											<c:otherwise>
												<a href="/collections/collection?id=<c:out value="${result.id}" />">
											</c:otherwise>
										</c:choose>
											<c:out value="${result.title}" escapeXml="false" />
										</a>
										<c:if test="${result.dateExpression != null}">
											<c:out value="${result.dateExpression}" />
										</c:if>																	
									</div>									
								</td>
							</tr>
						</c:forEach>
					</tbody>
				</table>
	
				<table class="archive-results-paging">
					<tbody><tr>
						<td></td>
						<td class="tools_right">
							<c:forEach items="${resultset.paging}" var="page" varStatus="pstatus">
								<c:choose>
									<c:when test="${page.name == currentPage}">
										<b><c:out value="${page.name}" /></b>
									</c:when>
									<c:otherwise>
										<a href="<c:out value="${baseUrl}" />?<c:out value="${page.query}" />"><c:out value="${page.name}" /></a>
									</c:otherwise>
								</c:choose>
							</c:forEach>	
						</td>
					</tr></tbody>
				</table>
			</td>		
		</tr>
	</table>
</div>

src/main/webapp/WEB-INF/jsp/search/configuration.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/portlet_2_0" prefix="portlet" %>
<%@ taglib uri="http://liferay.com/tld/aui" prefix="aui" %>
<%@ taglib uri="http://liferay.com/tld/portlet" prefix="liferay-portlet" %>
<%@ taglib uri="http://liferay.com/tld/theme" prefix="liferay-theme" %>
<%@ taglib uri="http://liferay.com/tld/ui" prefix="liferay-ui" %>
<%@ taglib uri="http://liferay.com/tld/util" prefix="liferay-util" %>

<%@page import="com.liferay.portlet.documentlibrary.model.DLFileEntryConstants" %><%@
page import="com.liferay.portlet.documentlibrary.model.DLFolderConstants" %><%@
page import="com.liferay.portlet.documentlibrary.service.DLAppLocalServiceUtil" %><%@
page import="com.liferay.portlet.documentlibrary.service.DLAppServiceUtil" %><%@
page import="com.liferay.portlet.documentlibrary.NoSuchFolderException" %><%@
page import="com.liferay.portlet.documentlibrary.util.DLUtil" %><%@
page import="com.liferay.portal.kernel.repository.RepositoryException" %><%@
page import="com.liferay.portal.kernel.repository.model.FileEntry" %><%@
page import="com.liferay.portal.kernel.repository.model.FileVersion" %><%@
page import="com.liferay.portal.kernel.repository.model.Folder" %><%@
page import="com.liferay.portal.kernel.util.FastDateFormatFactoryUtil" %><%@
page import="com.liferay.portal.kernel.util.HtmlUtil" %><%@
page import="com.liferay.portal.kernel.util.ParamUtil" %><%@
page import="com.liferay.portal.kernel.util.PrefsParamUtil" %>

<%@ page import="java.util.List" %><%@
page import="java.util.ArrayList" %><%@
page import="java.text.Format" %>

<%@ page import="javax.portlet.MimeResponse" %><%@
page import="javax.portlet.PortletConfig" %><%@
page import="javax.portlet.PortletContext" %><%@
page import="javax.portlet.PortletException" %><%@
page import="javax.portlet.PortletMode" %><%@
page import="javax.portlet.PortletPreferences" %><%@
page import="javax.portlet.PortletRequest" %><%@
page import="javax.portlet.PortletResponse" %><%@
page import="javax.portlet.PortletURL" %><%@
page import="javax.portlet.ResourceURL" %><%@
page import="javax.portlet.UnavailableException" %><%@
page import="javax.portlet.ValidatorException" %><%@
page import="javax.portlet.WindowState" %>

<%@ page import="com.liferay.portal.kernel.language.LanguageUtil" %><%@
page import="com.liferay.portal.kernel.util.Constants" %><%@
page import="com.liferay.portal.kernel.util.GetterUtil" %><%@
page import="com.liferay.portal.kernel.util.ParamUtil" %><%@
page import="com.liferay.portal.kernel.util.StringBundler" %><%@
page import="com.liferay.portal.kernel.util.StringPool" %><%@
page import="com.liferay.portal.kernel.util.Validator" %><%@
page import="com.liferay.portlet.PortletPreferencesFactoryUtil" %>

<liferay-theme:defineObjects />

<portlet:defineObjects />

<%
PortletPreferences preferences = renderRequest.getPreferences();

String portletResource = ParamUtil.getString(request, "portletResource");

if (Validator.isNotNull(portletResource)) {
	preferences = PortletPreferencesFactoryUtil.getPortletSetup(request, portletResource);
}

String button = PrefsParamUtil.getString(preferences, request, "button", "");
String url = PrefsParamUtil.getString(preferences, request, "url", "");
String view = PrefsParamUtil.getString(preferences, request, "view", "");
String code = PrefsParamUtil.getString(preferences, request, "code", "");
String contentType = PrefsParamUtil.getString(preferences, request, "contentType", "");
String dateExpression = PrefsParamUtil.getString(preferences, request, "dateExpression", "");
String collection = PrefsParamUtil.getString(preferences, request, "collection", "");
String language = PrefsParamUtil.getString(preferences, request, "language", "");
String sort = PrefsParamUtil.getString(preferences, request, "sort", "");
String parms = PrefsParamUtil.getString(preferences, request, "parms", "");
String size = PrefsParamUtil.getString(preferences, request, "size", "10");
String description = PrefsParamUtil.getString(preferences, request, "description", "");
String summary = PrefsParamUtil.getString(preferences, request, "summary", "");
String detailPage = PrefsParamUtil.getString(preferences, request, "detailPage", "");
String maxFieldSize = PrefsParamUtil.getString(preferences, request, "maxFieldSize", "");
String allResults = PrefsParamUtil.getString(preferences, request, "all-results", "true");
%>

<liferay-portlet:actionURL portletConfiguration="true" var="configurationURL" />

<aui:form action="<%= configurationURL %>" method="post">
	<aui:input name="<%= Constants.CMD %>" type="hidden" value="<%= Constants.UPDATE %>" />
		
	<aui:select label="View Selection" name="preferences--view--">
		<aui:option selected="<%= view.equals(\"results.jsp\") %>" value="results.jsp">Search & Navigation</aui:option>
		<aui:option selected="<%= view.equals(\"results2.jsp\") %>" value="results2.jsp">Search & Navigation 2</aui:option>
		<aui:option selected="<%= view.equals(\"videos.jsp\") %>" value="videos.jsp">Videos</aui:option>
		<aui:option selected="<%= view.equals(\"gallery1.jsp\") %>" value="gallery1.jsp">Zoomify Gallery</aui:option>
		<aui:option selected="<%= view.equals(\"gallery2.jsp\") %>" value="gallery2.jsp">Zoomify Gallery w/ Navigation</aui:option>
		<aui:option selected="<%= view.equals(\"collections.jsp\") %>" value="collections.jsp">Collection Search</aui:option>
		<aui:option selected="<%= view.equals(\"archive_results.jsp\") %>" value="archive_results.jsp">Archive Search</aui:option>
		<aui:option selected="<%= view.equals(\"notable_figures_entries.jsp\") %>" value="notable_figures_entries.jsp">Notable Figures Entries</aui:option>
		<aui:option selected="<%= view.equals(\"series.jsp\") %>" value="series.jsp">Series Listing</aui:option>
		<aui:option selected="<%= view.equals(\"series_with_notes.jsp\") %>" value="series_with_notes.jsp">Series Listing (with notes)</aui:option>
		<aui:option selected="<%= view.equals(\"subject_guides.jsp\") %>" value="subject_guides.jsp">Subject Guides</aui:option>
		<aui:option selected="<%= view.equals(\"cooke-results.jsp\") %>" value="cooke-results.jsp">Cooke Results (deprecated)</aui:option>
	</aui:select>
	
	<aui:input name="preferences--all-results--" type="checkbox" value="<%= allResults %>" label="Display All Results" />
	
	<aui:input name="preferences--code--" value="<%= code %>" label="Collection Code" />
	
	<aui:input name="preferences--sort--" value="<%= sort %>" />
	
	<aui:input name="preferences--size--" value="<%= size %>" style="width:100px;" />
	
	<aui:input name="preferences--parms--" value="<%= parms %>" />
	
	<aui:input name="preferences--detailPage--" label="Detail Page" value="<%= detailPage %>" />
	
	<aui:input name="preferences--maxFieldSize--" label="Maximum Field Size" style="width:100px;" value="<%= maxFieldSize %>" />
	
	<aui:input name="preferences--contentType--" type="checkbox" value="<%= contentType %>" />
	
	<aui:input name="preferences--dateExpression--" type="checkbox" value="<%= dateExpression %>" />
	
	<aui:input name="preferences--collection--" type="checkbox" value="<%= collection %>" />
	
	<aui:input name="preferences--description--" type="checkbox" value="<%= description %>" />
	
	<aui:input name="preferences--summary--" type="checkbox" value="<%= summary %>" />
	
	<aui:input name="preferences--language--" type="checkbox" value="<%= language %>" />
	
	<aui:button-row>
		<aui:button type="submit" />
	</aui:button-row>
</aui:form>

src/main/webapp/WEB-INF/jsp/search/default.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/portlet_2_0" prefix="portlet" %>
<%@ taglib uri="http://liferay.com/tld/theme" prefix="liferay-theme" %>
<%@ taglib uri="http://liferay.com/tld/ui" prefix="liferay-ui" %>

<portlet:defineObjects />
<liferay-theme:defineObjects />	
<%
String themeImagePath = themeDisplay.getPathThemeImages();
%>

<c:if test="${not empty result.weblinks}">
	<c:forEach items="${result.weblinks}" var="file" varStatus="nstatus">
		<c:if test="${file.type == 'rendition' || file.type == 'flippingbook'}">
			<c:set var="linked" scope="session" value="true"/>
			<iframe style="width:98%;height:700px;" src="<c:out value="${file.url}" />"></iframe>
		</c:if>
		<c:if test="${file.type == 'partner'}">
			<c:set var="linked" scope="session" value="true"/>
			<a href="<c:out value="${file.url}" />" target="_blank">
				<img src="<%=themeImagePath %>/collections/<c:out value="${result.collectionId}" />_large.jpg" alt="<c:out value="${result.collectionName}" escapeXml="false" />" />
			</a>
		</c:if>
	</c:forEach>
</c:if>